package pkg_Chat;

import java.awt.Dimension;
import javax.swing.JLabel;


public class Ventana_Chat extends javax.swing.JFrame {
    
    Persona persona;
    Chat chat;
    int last;
    
    /** Creates new form Ventana1_chat */
    public Ventana_Chat() {
        initComponents();
    }
    
    // Constructor recibe el nombre de la Persona y el Chat
    //      al que pertenece. Crea la Persona como tal.
    //      last le dice dede donde debe actualizar los Mensajes
    //      en el vector del Chat. Se agrega a si mismo al
    //      vector de Ventanas en el Main.
    public Ventana_Chat(String nombre, Chat chat) {
        persona = new Persona(nombre);
        last = 0;
        this.chat = chat;
        this.setTitle("Chat de " + nombre);
        initComponents();
        Main.ventanas.add(this);
        this.refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        enviar_btn = new javax.swing.JButton();
        Texto_mensaje_pane = new javax.swing.JScrollPane();
        Texto_mensaje = new javax.swing.JTextArea();
        Display_pnl = new javax.swing.JPanel();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enviar_btn.setText("enviar");
        enviar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_btnMouseClicked(evt);
            }
        });
        enviar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_btnActionPerformed(evt);
            }
        });

        Texto_mensaje.setColumns(20);
        Texto_mensaje.setRows(5);
        Texto_mensaje_pane.setViewportView(Texto_mensaje);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Texto_mensaje_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviar_btn)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Texto_mensaje_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(enviar_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Display_pnlLayout = new javax.swing.GroupLayout(Display_pnl);
        Display_pnl.setLayout(Display_pnlLayout);
        Display_pnlLayout.setHorizontalGroup(
            Display_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Display_pnlLayout.setVerticalGroup(
            Display_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Display_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Display_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_btnMouseClicked
        
    }//GEN-LAST:event_enviar_btnMouseClicked
   
    // Actualiza los Mensajes en la ventana.
    public void refresh ( ){
        for( ; last < chat.mensajes.size() ; last ++ ){
            list1.add( chat.mensajes.get(last).toString() );
        }
    }
    
    // Cuando se oprime el boton:
    //      Agrega el Mensaje nuevo al Chat, incluyendo la persona que lo mandó
    //      Llama la función en el Main que actualiza los mensajes para todos.
    private void enviar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_btnActionPerformed
        chat.mensajes.add( new Mensaje( persona , Texto_mensaje.getText() ) );
        Display_pnl.revalidate();
        Display_pnl.repaint();
        Texto_mensaje.setText("");
        Main.refresh();
    }//GEN-LAST:event_enviar_btnActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        
    }//GEN-LAST:event_list1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display_pnl;
    private javax.swing.JTextArea Texto_mensaje;
    private javax.swing.JScrollPane Texto_mensaje_pane;
    private javax.swing.JButton enviar_btn;
    private javax.swing.JPanel jPanel2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

}
